---
environment:
  author: Christian Berendt
  repository_server: https://github.com
  repository: thecloudsphere/registry
  name: python/base
  image: harbor.services.osism.tech/thecloudsphere/python/base
  command: /environment/run.sh
  versions:
    - version: "3.10"
  description: |
    Python is a programming language that lets you work quickly
    and integrate systems more effectively.
  inputs: []
  outputs: []
