---
blueprint:
  author: Christian Berendt
  repository_server: https://github.com
  repository: timontech/registry
  name: terraform/openstack/minimal
  versions:
    - version: main
  description: |
    Start a single instance on an OpenStack environment
  schedule: "*/15 * * * *"

  environment:
    repository: timontech/registry
    name: terraform/openstack
    version: 1.3.2

  inputs:
    - name: clouds.yaml
      destination:
        path: clouds.yaml
        type: file
      required: true
      description: |
        clouds.yaml is a configuration file that contains everything needed to connect
        to one or more clouds. It may contain private information and is generally
        considered private to a user.
      visibility: private

    - name: cloud name
      destination:
        path: TF_VAR_provider_cloud
        type: environment
      default: openstack
      required: false
      description: |
        Entry from the clouds.yaml to be used.

    - name: prefix
      destination:
        path: TF_VAR_prefix
        type: environment
      default: timon
      required: false
      description: |
        Prefix for the create resources to be used.

    - name: flavor
      destination:
        path: TF_VAR_flavor
        type: environment
      default: "SCS-1V:4:10"
      required: false
      description: |
        Machine flavor

    - name: image
      destination:
        path: TF_VAR_image
        type: environment
      default: Ubuntu 22.04
      required: false
      description: |
        Machine image

    - name: public network
      destination:
        path: TF_VAR_public_network
        type: environment
      default: external
      required: false
      description: |
        Public network

  outputs:
    - name: private_key
      source:
        path: private_key
        type: ssh
      description: |
        Private SSH key to access the instance
      visibility: private

    - name: address
      source:
        path: address
        type: ipv4address
      description: |
        IP address to access the instance
