---
blueprint:
  author: Christian Berendt
  repository_server: https://github.com
  repository: thecloudsphere/registry
  name: terraform/openstack/osism
  versions:
    - version: main
  description: |
    Start an OSISM testbed on an OpenStack environment

  environment:
    repository: thecloudsphere/registry
    name: terraform/openstack
    version: 1.3.2
    overrides:
      blueprint_source: https://github.com/osism/testbed.git
      # blueprint_source_key:
      # blueprint_version:
      working_directory: /processing/terraform
      outputs_directory: /processing/terraform
      # makefile:
      # makefile_pre_processing:
      makefile_processing: /processing/terraform/Makefile
      # makefile_post_processing:

  inputs:
    - name: clouds.yaml
      destination:
        path: clouds.yaml
        type: file
      required: true
      description: |
        clouds.yaml is a configuration file that contains everything needed to connect
        to one or more clouds. It may contain private information and is generally
        considered private to a user.
      visibility: private

    - name: environment
      destination:
        path: ENVIRONMENT
        type: environment
      default: betacloud
      required: false
      description: |
        Environment to use.

  outputs:
    - name: private_key
      source:
        path: ".id_rsa.{{ inputs.environment }}"
        type: ssh
      description: |
        Private SSH key to access the manager instance
      visibility: private

    - name: address
      source:
        path: ".MANAGER_ADDRESS.{{ inputs.environment }}"
        type: ipv4address
      description: |
        IP address to access the manager instance
