---
environment:
  author: Christian Berendt
  repository_server: https://github.com
  repository: thecloudsphere/registry
  name: terraform/azure
  image: harbor.services.osism.tech/thecloudsphere/terraform/azure
  command: /environment/run.sh
  versions:
    - version: 1.3.2
  description: |
    terraform/base environment with pre-installed Azure provider plugin
  inputs: []
  outputs: []
