---
environment:
  author: Christian Berendt
  repository_server: https://github.com
  repository: timontech/environments
  name: terraform/azure
  image: harbor.services.osism.tech/timon/terraform/azure
  command: /environment/run.sh
  versions:
    - 1.2.7
  description: |
    terraform/base environment with pre-installed Azure provider plugin
