---
- name: Destroy openstack/hello-world
  hosts: localhost
  connection: local

  vars:
    state: absent
    prefix: "{{ lookup('ansible.builtin.env', 'ANSIBLE_VAR_prefix', default='tcs') }}"
    provider_cloud: "{{ lookup('ansible.builtin.env', 'ANSIBLE_VAR_provider_cloud', default='openstack') }}"

  tasks:
    - name: "Destroy {{ prefix }}-instance"
      openstack.cloud.server:
        cloud: "{{ provider_cloud }}"
        state: "{{ state }}"
        name: "{{ prefix }}-instance"

    - name: "Destroy {{ prefix }}-keypair"
      openstack.cloud.keypair:
        cloud: "{{ provider_cloud }}"
        state: "{{ state }}"
        name: "{{ prefix }}-keypair"

    - name: "Destroy {{ prefix}}-secgroup"
      openstack.cloud.security_group:
        cloud: "{{ provider_cloud }}"
        state: "{{ state }}"
        name: "{{ prefix }}-secgroup"

    - name: "Destroy {{ prefix }}-router"
      openstack.cloud.router:
        cloud: "{{ provider_cloud }}"
        state: "{{ state }}"
        name: "{{ prefix }}-router"

    - name: "Destroy {{ prefix }}-subnet"
      openstack.cloud.subnet:
        cloud: "{{ provider_cloud }}"
        state: "{{ state }}"
        name: "{{ prefix }}-subnet"

    - name: "Destroy {{ prefix }}-network"
      openstack.cloud.network:
        cloud: "{{ provider_cloud }}"
        state: "{{ state }}"
        name: "{{ prefix }}-network"

