---
name: Build kubernetes kubectl container image

"on":
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-kubectl-base-container-image.yml
      - environments/kubectl/base/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-kubectl-base-container-image.yml
      - environments/kubectl/base/**

jobs:

  build-kubectl-base-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.24.10
          - 1.25.6
          - 1.26.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: kubernetes/kubectl
          REPOSITORY: thecloudsphere/kubernetes/kubectl
          VERSION: ${{ matrix.version }}

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: kubernetes/kubectl
          REPOSITORY: thecloudsphere/kubernetes/kubectl
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'thecloudsphere/registry' &&
          github.ref == 'refs/heads/main'
