---
name: Validate blueprints

"on":
  push:
    paths:
      - .github/workflows/validate-blueprints.yml
      - blueprints/schema.yaml
      - blueprints/**/.tcs.yml
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/validate-blueprints.yml
      - blueprints/schema.yaml
      - blueprints/**/.tcs.yml

jobs:
  validate-blueprints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip3 install yamale ruamel.yaml
      - run: find blueprints -name .tcs.yaml | xargs -n1 yamale -s blueprints/schema.yaml -p ruamel
